apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mender
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-07T17:00:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: workflows
    app.kubernetes.io/instance: mender
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: create-artifact-worker
    app.kubernetes.io/part-of: mender
    helm.sh/chart: mender
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:helm.sh/chart: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app.kubernetes.io/name: {}
          f:spec:
            f:containers:
              k:{"name":"workflows"}:
                .: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"CREATE_ARTIFACT_DEPLOYMENTS_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CREATE_ARTIFACT_GATEWAY_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:envFrom: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: Go-http-client
    operation: Update
    time: "2021-04-07T17:00:30Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-07T17:00:38Z"
  name: create-artifact-worker
  namespace: default
  resourceVersion: "8912"
  uid: c87371fc-9ea7-4fb9-b920-3845be9a7b2a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: create-artifact-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: create-artifact-worker
    spec:
      containers:
      - command:
        - workflows
        - --config
        - /etc/workflows/config.yaml
        - worker
        - --automigrate
        env:
        - name: CREATE_ARTIFACT_GATEWAY_URL
          value: https://mender-api-gateway
        - name: CREATE_ARTIFACT_DEPLOYMENTS_URL
          value: http://mender-deployments:8080
        envFrom:
        - prefix: WORKFLOWS_
          secretRef:
            name: mongodb-common
        image: docker.io/mendersoftware/create-artifact-worker:mender-2.5.0
        imagePullPolicy: IfNotPresent
        name: workflows
        resources:
          limits:
            cpu: 500m
            memory: 128M
          requests:
            cpu: 100m
            memory: 50M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-07T17:00:31Z"
    lastUpdateTime: "2021-04-07T17:00:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-07T17:00:30Z"
    lastUpdateTime: "2021-04-07T17:00:38Z"
    message: ReplicaSet "create-artifact-worker-5b4b445cd5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
