apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mender
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-07T17:00:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: deployments
    app.kubernetes.io/instance: mender
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deployments
    app.kubernetes.io/part-of: mender
    helm.sh/chart: mender
  name: deployments
  namespace: default
  resourceVersion: "8963"
  uid: 1cfc0a85-f5ee-4a49-9045-91b789ccc35a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: deployments
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: deployments
    spec:
      containers:
      - args:
        - server
        - --automigrate
        env:
        - name: DEPLOYMENTS_MIDDLEWARE
          value: prod
        - name: DEPLOYMENTS_AWS_TAG_ARTIFACT
          value: "true"
        envFrom:
        - prefix: DEPLOYMENTS_
          secretRef:
            name: mongodb-common
        - prefix: DEPLOYMENTS_
          secretRef:
            name: s3-artifacts
        image: docker.io/mendersoftware/deployments:mender-2.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/internal/v1/deployments/alive
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: deployments
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/internal/v1/deployments/health
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128M
          requests:
            cpu: 200m
            memory: 50M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-07T17:00:31Z"
    lastUpdateTime: "2021-04-07T17:00:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-07T17:00:30Z"
    lastUpdateTime: "2021-04-07T17:00:49Z"
    message: ReplicaSet "deployments-5ff8ffb79" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
