apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mender
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-07T17:00:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: gui
    app.kubernetes.io/instance: mender
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gui
    app.kubernetes.io/part-of: mender
    helm.sh/chart: mender
  name: gui
  namespace: default
  resourceVersion: "9049"
  uid: ef482173-8eae-4028-ac81-9c09e0845246
spec:
  minReadySeconds: 120
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: gui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: gui
    spec:
      containers:
      - env:
        - name: HAVE_MULTITENANT
          value: "true"
        - name: GATEWAY_IP
          value: k8s.hosted.mender.io
        - name: GATEWAY_PORT
          value: "443"
        image: docker.io/mendersoftware/gui:mender-2.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        name: gui
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128M
          requests:
            cpu: 100m
            memory: 50M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-07T17:00:30Z"
    lastUpdateTime: "2021-04-07T17:00:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-07T17:00:30Z"
    lastUpdateTime: "2021-04-07T17:02:42Z"
    message: ReplicaSet "gui-6df6bf778d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
