apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mender
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-07T17:00:30Z"
  generation: 1
  labels:
    app.kubernetes.io/component: useradm
    app.kubernetes.io/instance: mender
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: useradm
    app.kubernetes.io/part-of: mender
    helm.sh/chart: mender
  name: useradm
  namespace: default
  resourceVersion: "8950"
  uid: 9657bdfb-881b-400a-b0e8-63464250b9f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: useradm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: useradm
    spec:
      containers:
      - args:
        - server
        - --automigrate
        env:
        - name: USERADM_MIDDLEWARE
          value: prod
        - name: USERADM_JWT_ISSUER
          value: Mender Users
        - name: USERADM_JWT_EXP_TIMEOUT
          value: "604800"
        - name: USERADM_SERVER_PRIV_KEY_PATH
          value: /etc/useradm/rsa/private.pem
        - name: USERADM_MIDDLEWARE
          value: prod
        - name: USERADM_TOTP_ISSUER
          value: Mender
        envFrom:
        - prefix: USERADM_
          secretRef:
            name: mongodb-common
        image: docker.io/mendersoftware/useradm:mender-2.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/internal/v1/useradm/alive
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: useradm
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/internal/v1/useradm/health
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128M
          requests:
            cpu: 100m
            memory: 50M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/useradm/rsa/
          name: rsa
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rsa
        secret:
          defaultMode: 420
          secretName: rsa-useradm
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-07T17:00:31Z"
    lastUpdateTime: "2021-04-07T17:00:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-07T17:00:30Z"
    lastUpdateTime: "2021-04-07T17:00:47Z"
    message: ReplicaSet "useradm-844cd87cd4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
