apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    docker.io/hostpath: /var/lib/k8s-pvs/mongodb/pvc-47cacc3c-9966-4eba-afe5-d1c13d5e9953
    pv.kubernetes.io/provisioned-by: docker.io/hostpath
  name: pvc-47cacc3c-9966-4eba-afe5-d1c13d5e9953
  resourceVersion: "849482"
  selfLink: /api/v1/persistentvolumes/pvc-47cacc3c-9966-4eba-afe5-d1c13d5e9953
  uid: 1632dc93-bda2-4292-8b60-cec148bcca52
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongodb
    namespace: default
    resourceVersion: "849471"
    uid: 47cacc3c-9966-4eba-afe5-d1c13d5e9953
  hostPath:
    path: /var/lib/k8s-pvs/mongodb/pvc-47cacc3c-9966-4eba-afe5-d1c13d5e9953
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  volumeMode: Filesystem
status:
  phase: Bound
