apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    hostPathProvisionerIdentity: 20d6790e-d3d9-4960-b8bc-185b25e37037
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  name: pvc-39c67df2-9fd3-4e61-a7ff-6b3ab4335a99
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: minio
    namespace: default
  hostPath:
    path: /tmp/hostpath-provisioner/default/minio
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem