apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: minio
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-07T16:59:35Z"
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-6.0.5
    heritage: Helm
    release: minio
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:release: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-04-07T16:59:35Z"
  name: minio
  namespace: default
  resourceVersion: "8626"
  uid: 5240faa8-b1f4-499b-ba8f-6b6da4b8b201
spec:
  clusterIP: 10.111.218.104
  clusterIPs:
  - 10.111.218.104
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    release: minio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
