apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1ERXdOVEV6TURreE4xb1hEVE14TURFd05ERXpNRGt4TjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG1zCkpPMkRIbXRSQWticjZaTTY3WXNMRkNkUzVGa0xvb1dXSm56R296UGduSGpyUTdsd1lwV3ZtdDh1Rnd6QitzN1cKendEQUpSSGpHT0lSeVFLMk5sZkxuWG9hSU4zK3JVcThWU216VHYwN0JsdGNWWWVybTNFa1lzZllGZ3ZtQkVvNwp1ZWJDSWhiU01lUEJZVjRYUGZxMG5SMlVwLy9qd25vaHlOaDB6cnY4Rm8xZDFmd3htSjRTVENHMytzMDdnOEhqCjNFa3F2bWkxZ2ZHVHpHdHM0eFJ4TkhlVURWUjZFSjVZRDhGcktoa2dZeGlXQUdzNzdLY2EyQnlyMy8rcmF4Y0EKYVZsVWdYbXNSV2FIa1VrVFN3TjNYWkpuTmdoYkN1WXFqRS9FY0o5ZkhVdy8ydm9jUGFxUVRXRUVhNU52d1BBTwptMEhDK0xWcTZldStaQ1ZQcEhVQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUaTNGeG9Xdm11ZHhaWDJkN2l3UGliRXRsNlJ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEUHFKdksySgpleUk3alRlR1N5c2xQb0JIQmFRWjBKekdzR0JndTN5Z3dtdEdrekVUb3l0WFFzb21RWHA3TjZaYWtCUVpLNWY5CjVzaHFzUWI1Q2tSRnpvOEsycUc0dGl6WldWRUd2MVdhRFdkVHNuWWhRS1dIbml3eG1XZVNzekE3Yjl4dlFXU1IKcXNDR3VoenMzY0N2OXpKa1h2VXhTdUJWdTBqT0lzQlR6VlhaZ20vMGRiRXQ0bSs0em5rUTdsL05yNU5hRm04LwpwWUk3N3RjZ3AyRTZQTkwwbm1peEkyL2FhajNrY2lYWmRMNHp1OTBlZlZDRm5Rbmc4bCs5YnJlMG5nTlNZU0hlCnpFTE1uNWE2OHdOSjJLMHdjMmpPZlduaDJZTTNsbnZoeTlCQ0tMQUtSRC8zQjlrZzNWeENRN3liaDZSV05ZWmsKYjBJMWxJUlJRbTI3Vnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: ZGVmYXVsdA==
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqZ3dkRmxOYlRSM1RFZGFXR001ZWxoa2QxOXBXV2hUWjBKVU5teG5UMjkwTmxCdFZVOXFRa05ZU3pBaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbTFwYm1sdkxYUnZhMlZ1TFhSbWMzaHVJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1Ym1GdFpTSTZJbTFwYm1sdklpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaVl6aGxZamszWW1ZdE0yVTROQzAwTkdVd0xUZ3daVE10TkdJME1ESXpaamRoWVRNMUlpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbVJsWm1GMWJIUTZiV2x1YVc4aWZRLmliX0pPRDNrcnQ5aEEtWnBiOFh0a1k1WGJ5NGhlaDBoRTFVOWdhVEdSblhnZGhsTkU3a0l0NE4ySjg5R0RYbkFTbkhlbklVWHJGUmFuUnkwS1ZqcWFZMTVPSG9yRENMeFBuOTZSU244b3p2TjR6Z1VfRWN0SU16eEN1bnlEMG9JdENFU1NROGhTV2toRUxQMVRIUEJJSnZ0T0NoUzdYTG1zQnp3U1NRZXNtai1xckFQOHBBcVBCVUFNbmR5bWdkYmhSTmZmOHViaFcyWU5GdXBPWWhQNEtraTZBMzByWHpReFBCR1BzTG1UWmt5ejZvaVI3VERZa1hyOW9vdzBxMFZvRzY0N3lvLUxISlNMUlFDVWZqSmZxa2Jia1AxdTNqRmpzcmxtQUJMSGZvdjBwNXdIQlJQT1ZQYzUtaUNOUk04bU9tVlhScEkzVDlTcFJTM1lkUEh3Zw==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: minio
    kubernetes.io/service-account.uid: c8eb97bf-3e84-44e0-80e3-4b4023f7aa35
  creationTimestamp: "2021-04-07T16:59:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-07T16:59:35Z"
  name: minio-token-tfsxn
  namespace: default
  resourceVersion: "8611"
  uid: dd610fe8-ad5c-4c04-954a-0805de09e37f
type: kubernetes.io/service-account-token
