apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1ERXdOVEV6TURreE4xb1hEVE14TURFd05ERXpNRGt4TjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG1zCkpPMkRIbXRSQWticjZaTTY3WXNMRkNkUzVGa0xvb1dXSm56R296UGduSGpyUTdsd1lwV3ZtdDh1Rnd6QitzN1cKendEQUpSSGpHT0lSeVFLMk5sZkxuWG9hSU4zK3JVcThWU216VHYwN0JsdGNWWWVybTNFa1lzZllGZ3ZtQkVvNwp1ZWJDSWhiU01lUEJZVjRYUGZxMG5SMlVwLy9qd25vaHlOaDB6cnY4Rm8xZDFmd3htSjRTVENHMytzMDdnOEhqCjNFa3F2bWkxZ2ZHVHpHdHM0eFJ4TkhlVURWUjZFSjVZRDhGcktoa2dZeGlXQUdzNzdLY2EyQnlyMy8rcmF4Y0EKYVZsVWdYbXNSV2FIa1VrVFN3TjNYWkpuTmdoYkN1WXFqRS9FY0o5ZkhVdy8ydm9jUGFxUVRXRUVhNU52d1BBTwptMEhDK0xWcTZldStaQ1ZQcEhVQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUaTNGeG9Xdm11ZHhaWDJkN2l3UGliRXRsNlJ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEUHFKdksySgpleUk3alRlR1N5c2xQb0JIQmFRWjBKekdzR0JndTN5Z3dtdEdrekVUb3l0WFFzb21RWHA3TjZaYWtCUVpLNWY5CjVzaHFzUWI1Q2tSRnpvOEsycUc0dGl6WldWRUd2MVdhRFdkVHNuWWhRS1dIbml3eG1XZVNzekE3Yjl4dlFXU1IKcXNDR3VoenMzY0N2OXpKa1h2VXhTdUJWdTBqT0lzQlR6VlhaZ20vMGRiRXQ0bSs0em5rUTdsL05yNU5hRm04LwpwWUk3N3RjZ3AyRTZQTkwwbm1peEkyL2FhajNrY2lYWmRMNHp1OTBlZlZDRm5Rbmc4bCs5YnJlMG5nTlNZU0hlCnpFTE1uNWE2OHdOSjJLMHdjMmpPZlduaDJZTTNsbnZoeTlCQ0tMQUtSRC8zQjlrZzNWeENRN3liaDZSV05ZWmsKYjBJMWxJUlJRbTI3Vnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: ZGVmYXVsdA==
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqZ3dkRmxOYlRSM1RFZGFXR001ZWxoa2QxOXBXV2hUWjBKVU5teG5UMjkwTmxCdFZVOXFRa05ZU3pBaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbTFwYm1sdkxYVndaR0YwWlMxd2NtOXRaWFJvWlhWekxYTmxZM0psZEMxMGIydGxiaTFzZDJnMmRpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSnRhVzVwYnkxMWNHUmhkR1V0Y0hKdmJXVjBhR1YxY3kxelpXTnlaWFFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUptWXpZMk1XUmxNaTB3WTJFNUxUUTVZelV0WW1VMk15MWhaV05oWVdZMk56Rm1ZV1lpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpHVm1ZWFZzZERwdGFXNXBieTExY0dSaGRHVXRjSEp2YldWMGFHVjFjeTF6WldOeVpYUWlmUS5zZm1hSHJSc1JTVDB3dS1pNkRmUEh5OFR4SXhmeVlxVXFLQnZCM0VLVktFZm0xbWtGVy1rWGZVM2tuemx5RE5BX0NNai1xXy1sa1Rrai15UWJCRGNCalhfdGZWcXlWa3NpS2QyZVk4Wkd3X00zSEJIT1FsamVFVFF3UnIwMkFmVzlqZzRvYlNnaHhGdXdxSHRsMHVxWkVvWW5aU25neml5ZzNpMnJlbUc3d3c1T2xyLS15ZWNoZFNoTGlVVEttWTN6MEtuY2Zkb2JySmJrSDhVSUU3YmZpSVgwZHA3bFpKNjBLOW4wVTlETmR5RWpncVRhNzBESkpqS3lJNElydTFRNzBLSlFhTlB3OG4tMlJmNVlGNTFrZTFMZ1pjU1JjOTdNU2FhRFhjYnRnWXJtSkN4TUlNNms5S3E0ZldHX2lXLTMtYVJlVy03WGlYQlFmQngyWDYtZFE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: minio-update-prometheus-secret
    kubernetes.io/service-account.uid: fc661de2-0ca9-49c5-be63-aecaaf671faf
  creationTimestamp: "2021-04-07T16:59:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-07T16:59:35Z"
  name: minio-update-prometheus-secret-token-lwh6v
  namespace: default
  resourceVersion: "8612"
  uid: 659fac2c-fcfc-44df-a21f-00ff4b31eb7d
type: kubernetes.io/service-account-token
