apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1ERXdOVEV6TURreE4xb1hEVE14TURFd05ERXpNRGt4TjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG1zCkpPMkRIbXRSQWticjZaTTY3WXNMRkNkUzVGa0xvb1dXSm56R296UGduSGpyUTdsd1lwV3ZtdDh1Rnd6QitzN1cKendEQUpSSGpHT0lSeVFLMk5sZkxuWG9hSU4zK3JVcThWU216VHYwN0JsdGNWWWVybTNFa1lzZllGZ3ZtQkVvNwp1ZWJDSWhiU01lUEJZVjRYUGZxMG5SMlVwLy9qd25vaHlOaDB6cnY4Rm8xZDFmd3htSjRTVENHMytzMDdnOEhqCjNFa3F2bWkxZ2ZHVHpHdHM0eFJ4TkhlVURWUjZFSjVZRDhGcktoa2dZeGlXQUdzNzdLY2EyQnlyMy8rcmF4Y0EKYVZsVWdYbXNSV2FIa1VrVFN3TjNYWkpuTmdoYkN1WXFqRS9FY0o5ZkhVdy8ydm9jUGFxUVRXRUVhNU52d1BBTwptMEhDK0xWcTZldStaQ1ZQcEhVQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUaTNGeG9Xdm11ZHhaWDJkN2l3UGliRXRsNlJ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEUHFKdksySgpleUk3alRlR1N5c2xQb0JIQmFRWjBKekdzR0JndTN5Z3dtdEdrekVUb3l0WFFzb21RWHA3TjZaYWtCUVpLNWY5CjVzaHFzUWI1Q2tSRnpvOEsycUc0dGl6WldWRUd2MVdhRFdkVHNuWWhRS1dIbml3eG1XZVNzekE3Yjl4dlFXU1IKcXNDR3VoenMzY0N2OXpKa1h2VXhTdUJWdTBqT0lzQlR6VlhaZ20vMGRiRXQ0bSs0em5rUTdsL05yNU5hRm04LwpwWUk3N3RjZ3AyRTZQTkwwbm1peEkyL2FhajNrY2lYWmRMNHp1OTBlZlZDRm5Rbmc4bCs5YnJlMG5nTlNZU0hlCnpFTE1uNWE2OHdOSjJLMHdjMmpPZlduaDJZTTNsbnZoeTlCQ0tMQUtSRC8zQjlrZzNWeENRN3liaDZSV05ZWmsKYjBJMWxJUlJRbTI3Vnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: ZGVmYXVsdA==
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqZ3dkRmxOYlRSM1RFZGFXR001ZWxoa2QxOXBXV2hUWjBKVU5teG5UMjkwTmxCdFZVOXFRa05ZU3pBaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbTF2Ym1kdlpHSXRkRzlyWlc0dGMyYzVaaklpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pYlc5dVoyOWtZaUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJbU0zWmpreE5qTTRMVFJrWkRRdE5ERTVNUzFoTkRZeExUZGtabVF4WldNM01XVmhZaUlzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT20xdmJtZHZaR0lpZlEuZkFwYXJuaEg2TUUwazlnYTl1QW1qZDhkaUhJY3B1bUxzd0I1amJZUG55MG81bE5WSlNONUFDNXhZN252bDdNVmNENGpRWDNCYkZKZUg4VHAwZU9EcndWSUUzRFloMTMybHBxZ1k0VGtYOGM2S3lpVkJmNFBYRW5JcGxjeFUyZFJqX1RrYjZGYXlkZGpRaUZ6bGFLUmNOWXV4SU90Mkw1LVNTU3Y0ZDYtc3YwbUlSOHV6OWFBcGQzbEVwNl9oQnhmUFI2dXlFYXhoVXVQMGZieEotMmdJOTNNUkpIY0N0Zi1FR0pJanJhOEFRTE1FdjNnRjcwVlUxMmdGQS1oZTE0amNYd2dORW1PWVR2b3JESURSTFRYbHRNNFR5aVlIakJVSy16S3RHTktfZjNxeTl2Ynhab0ZwREZab0o1RzE3OURtdHlnRmFiSWZ2VWhkVElQMEZLeEJ3
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: mongodb
    kubernetes.io/service-account.uid: c7f91638-4dd4-4191-a461-7dfd1ec71eab
  creationTimestamp: "2021-04-07T14:52:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-07T14:52:00Z"
  name: mongodb-token-sg9f2
  namespace: default
  resourceVersion: "468"
  uid: ad71f352-ec41-45a6-9466-f5c51d6662f6
type: kubernetes.io/service-account-token
