apiVersion: v1
data:
  AWS_AUTH_KEY: bXlhY2Nlc3NrZXk=
  AWS_AUTH_SECRET: bXlzZWNyZXRrZXk=
  AWS_BUCKET: bWVuZGVyLWFydGlmYWN0cw==
  AWS_URI: aHR0cDovL21pbmlvOjkwMDA=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: mender
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-07T17:00:30Z"
  labels:
    app.kubernetes.io/component: secrets
    app.kubernetes.io/instance: mender
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: s3-artifacts
    app.kubernetes.io/part-of: mender
    helm.sh/chart: mender
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:AWS_AUTH_KEY: {}
        f:AWS_AUTH_SECRET: {}
        f:AWS_BUCKET: {}
        f:AWS_URI: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:helm.sh/chart: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-04-07T17:00:30Z"
  name: s3-artifacts
  namespace: default
  resourceVersion: "8699"
  uid: 68ab7a80-a31b-4638-af6f-a8fa3410653c
type: Opaque
